[target.'cfg(all(target_arch = "arm", target_os = "none"))']
runner = "probe-rs run --chip STM32H755ZITx"

[build]
target = "thumbv7em-none-eabihf"

[patch.'https://github.com/fishloa/embedded-tls.git']
embedded-tls = { path = "../embedded-tls-hw" }
